name: flappy_bird
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_fft: ^1.0.2+6
  lottie: ^2.7.0
  http: ^1.1.0
  path_provider: ^2.1.1
  rating_dialog: ^2.0.4
  audioplayers: ^5.2.0
  smooth_star_rating_null_safety: ^1.0.4+2
  share_plus: ^7.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  delayed_display: ^2.0.0
  anitex: ^2.0.0
  assets_audio_player: ^3.0.6
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
dependency_overrides:
  archive: ^3.4.6
  platform: ^3.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/pics/
    - assets/audio/
    - assets/
    - assets/audios/fast-simple-chop.mp3
    - assets/audios/level-up.mp3
    - assets/images/
    - assets/audios/
    - assets/lottie/
  fonts:
    - family: Magic4
      fonts:
        - asset: assets/fonts/DiloWorld-mLJLv.ttf

    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: RobotoMono-SemiBold
      fonts:
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
    - family: Paytone
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
    - family: Carter
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf