name: flappy_bird
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^9.0.0
  clock: any
  collection: any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_fft: ^1.0.2+6
  lottie: ^2.7.0
  http: ^1.1.0
  path_provider: ^2.1.1
  rating_dialog: ^2.0.4
  audioplayers: ^5.2.0
  smooth_star_rating_null_safety: ^1.0.4+2
  share_plus: ^7.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  delayed_display: ^2.0.0
  anitex: ^2.0.0
  assets_audio_player: ^3.0.6
  rflutter_alert: ^2.0.7
  flutter_bloc: ^9.1.0
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  intl: any
  meta: any
  package_info_plus: ^8.3.0
  path: any
  rxdart: 0.27.7
  shared_preferences: ^2.5.2
  stack_trace: any
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^3.0.0-0.0.dev  # Downgraded to a version that is compatible with hive_generator
  carapacik_lints: ^1.11.1
  flutter_gen_runner: ^5.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"

dependency_overrides:
  archive: ^3.4.6
  platform: ^3.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/pics/
    - assets/audio/
    - assets/
    - assets/audios/fast-simple-chop.mp3
    - assets/audios/level-up.mp3
    - assets/images/
    - assets/audios/
    - assets/lottie/
    - assets/dictionary/
    - assets/fonts/
  fonts:
    - family: Magic4
      fonts:
        - asset: assets/fonts/DiloWorld-mLJLv.ttf
    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: RobotoMono-SemiBold
      fonts:
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
    - family: Paytone
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
    - family: Carter
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 120

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/src/core/constant/localization/translations
  output_dir: lib/src/core/constant/localization/generated
